### PR TITLE
Protocol read0 sync

### PR DESCRIPTION
**Pull request by mbebenita**
Adds new test case and leaves the previous test case as is.

### CODE REVIEW

**Comment by mykmelez** [comment]
Sorry, @mbebenita, I didn't get notified about this PR, and I didn't notice it until now. I'll update my notification prefs to ensure I get notified the next time.

Note that I requested a pull for a slightly modified version of this StressBench in https://github.com/mozilla/j2me.js/pull/1529. You could merge that, or I could merge this into my protocol-read0-sync branch and close that PR.

Any preference?

**Comment by mykmelez** [comment]
(Hmm, GitHub says I'm watching this repo, so I dunno why I didn't get a notification.)

**Comment by mbebenita** [comment]
No preference. Go ahead and merge yours.

**Comment by mykmelez** [comment]
(I merged mine, so closing this PR.)

**Pull request closed without merging**
